[target.aarch64-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update && apt-get install -y --no-install-recommends libclang-dev protobuf-compiler && rm -rf /var/lib/apt/lists/*",
]
